import { Criterion } from "./criteria";

export const defaultCriteria: Criterion[] = [
  {
    id: "avg_revenue_6_12m",
    label: "Chiffre d’affaires moyen sur 6-12 mois",
    description: "Revenus mensuels moyens, stabilité et tendance",
    defaultWeight: 15,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
  {
    id: "tx_count",
    label: "Nombre de transactions",
    description: "Fréquence et régularité des ventes",
    defaultWeight: 10,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
  {
    id: "avg_tx_amount",
    label: "Montant moyen des transactions",
    description: "Taille moyenne des ventes",
    defaultWeight: 5,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
  {
    id: "cashflow_net",
    label: "Flux de trésorerie (encaissements vs dépenses)",
    description: "Capacité à générer des liquidités",
    defaultWeight: 10,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
  {
    id: "available_balance",
    label: "Solde disponible / liquidités",
    description: "Argent disponible pour remboursement",
    defaultWeight: 10,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
  {
    id: "debt_repayment_history",
    label: "Endettement existant / historique de remboursement",
    description: "Prêts en cours et respect des échéances",
    defaultWeight: 10,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
  {
    id: "payment_mix",
    label: "Répartition des modes de paiement",
    description: "Cash, Wave, Orange Money, cartes bancaires",
    defaultWeight: 5,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
  {
    id: "late_payment_incidents",
    label: "Retards ou incidents de paiement",
    description: "Historique des paiements manqués ou tardifs",
    defaultWeight: 10,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
  {
    id: "tx_consistency",
    label: "Fiabilité et cohérence des transactions",
    description: "Cohérence entre revenus déclarés et flux observés",
    defaultWeight: 5,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
  {
    id: "business_age",
    label: "Durée d’activité",
    description: "Plus un restaurant est ancien, plus il est stable",
    defaultWeight: 5,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
  {
    id: "avg_purchase_volume",
    label: "Volume moyen d’achats",
    description: "Achats réguliers et cohérents avec le chiffre d’affaires",
    defaultWeight: 5,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
  {
    id: "sales_variability",
    label: "Variabilité ou saisonnalité des ventes",
    description: "Fluctuations ou saisonnalité importante",
    defaultWeight: 5,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
  {
    id: "business_type",
    label: "Type de restaurant / commerce",
    description: "Fast-food, glacier, hôtel, etc.",
    defaultWeight: 2.5,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
  {
    id: "location",
    label: "Localisation",
    description: "Emplacement stratégique / zone à fort trafic",
    defaultWeight: 2.5,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
  {
    id: "reputation_reviews",
    label: "Réputation et avis clients",
    description: "Évaluations et feedback clients",
    defaultWeight: 2.5,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
  {
    id: "dcredit_engagement",
    label: "Engagement et utilisation de Mafalia",
    description: "Fréquence et qualité de l’utilisation",
    defaultWeight: 2.5,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
  {
    id: "market_stability",
    label: "Stabilité du marché",
    description: "Tendances sectorielles locales",
    defaultWeight: 2.5,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
  {
    id: "repayment_capacity",
    label: "Capacité de remboursement calculée",
    description: "Ratio revenu disponible / mensualité du prêt",
    defaultWeight: 10,
    customizable: true,
    minScore: 0,
    maxScore: 1,
  },
];
